version: "2"
run:
  concurrency: 4
  timeout: 5m
output:
  formats:
    text:
      colors: true
linters:
  disable-all: true
  enable:
  - errcheck
  - govet
  - ineffassign
  - staticcheck
  - unused
  - gosec
