# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: docker-setup

builds:
- main: ./cmd/docker-setup
  binary: docker-setup
  gobinary: helper/usr/local/bin/go
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.version={{.Version}}
  goos:
  - linux
  goarch:
  - amd64
  - arm64

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

sboms:
- id: foo
  cmd: helper/usr/local/bin/syft
  args: [ "${artifact}", "--output", "cyclonedx-json", "--file", "$document" ]
  documents:
  - ${artifact}.cyclonedx.json

archives:
- format: tar.gz
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "arm64" }}aarch64
    {{- else }}{{ .Arch }}{{ end }}
  files:
  - LICENSE

changelog:
  use: github
  sort: asc