# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: uniget

builds:
- main: ./cmd/uniget
  binary: uniget
  gobinary: helper/usr/local/bin/go
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.version={{.Version}}
  goos:
  - linux
  goarch:
  - amd64
  - arm64

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'

sboms:
- id: sbom
  cmd: helper/usr/local/bin/syft
  args: [ "${artifact}", "--output", "cyclonedx-json", "--file", "$document" ]
  documents:
  - ${artifact}.cyclonedx.json

archives:
- id: uniget
  format: tar.gz
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "arm64" }}aarch64
    {{- else }}{{ .Arch }}{{ end }}
  files:
  - LICENSE

changelog:
  use: github
  sort: asc

release:
  github:
    owner: nicholasdille
    name: uniget
  ids:
  - uniget
  name_template: "{{ .Version }}"
  mode: replace