blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/uniget-org/cli/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://docs.uniget.dev
    about: Check for usage and examples.
