name: Feature suggestion
description: Suggest an idea for this project
title: "[Feature]: "
labels:
- enhancement
body:

  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What are you missing?
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: your-suggestion
    attributes:
      label: What do you expect?
      description: Describe the solution you'd like

  - type: textarea
    id: alternatives
    attributes:
      label: Have you considered alternatives?
      description: Describe alternatives you've considered

  - type: textarea
    id: context
    attributes:
      label: What is the context?
      description: Describe why you need this and how it will help you
