name: auto-tag

on:
  #schedule:
  #- cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  auto-tag:
    name: auto-tag
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        fetch-depth: 0

    - name: Test
      run: |
        LAST_TAG="$( git describe --tags --abbrev=0 --exclude '*-*' )"
        echo "Checking commits since tag ${LAST_TAG}"

        if git log ${LAST_TAG}.. --pretty="%an" | grep -Fq 'renovate[bot]'; then
            echo "Unattended changes detected."

            if git log ${LAST_TAG}.. --pretty="%an" | grep -Fvq 'renovate[bot]'; then
                echo "Commit by developer(s) detected. Aborting."
            
            else
                echo "No authors/committers since last tag"

                echo "Creating patch"
                make patch
            fi

        else
            echo "No unattended commits detected. Aborting."
        fi
