name: deps

on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  deps:
    name: deps
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Bump deps
      run: |
        go get -u ./...

    - name: Tidy deps
      run: |
        go mod tidy

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
      with:
        commit_message: "Bump dependencies"
        file_pattern: 'go.mod go.sum'
