name: deps

on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch:

jobs:

  deps:
    name: deps
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Bump deps
      run: |
        go get -u ./...

    - name: Tidy deps
      run: |
        go mod tidy

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Bump dependencies"
        file_pattern: 'go.mod go.sum'
