name: Renovate
on:
  schedule:
  - cron: '15 * * * *'
  push:
    branches:
    - main
    paths:
    - .github/workflows/renovate.yml
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Self-hosted Renovate
      env:
        LOG_LEVEL: 'debug'
      uses: renovatebot/github-action@v36.0.0
      with:
        useSlim: true
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
