name: Renovate
on:
  schedule:
  - cron: '13 */2 * * *'
  pull_request:
    types:
    - edited
    - labeled
    - unlabeled
    - ready_for_review
    - synchronize
    - reopened
    branches:
    - "main"
  push:
    branches:
    - main
    paths:
    - .github/workflows/renovate.yml
  workflow_dispatch:

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: renovate/cache
        key: renovate-cache

    - name: Self-hosted Renovate
      env:
        LOG_LEVEL: debug
        RENOVATE_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        mkdir -p renovate/cache
        docker run --interactive --rm \
            --env LOG_LEVEL \
            --env RENOVATE_TOKEN \
            --volume $PWD/renovate:/tmp/renovate \
            renovate/renovate:slim \
                "${GITHUB_REPOSITORY}"

    - name: Save cache
      id: cache-save
      uses: actions/cache/save@v3
      with:
        path: renovate/cache
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}